name: dispatch CI

on:
  push:
    branches:
      - main
    paths:
      - 'dispatch/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Echo service name
        run: echo "Running dispatch pipeline"
